networks:
  envcard-network:
    driver: bridge

volumes:
  envcard-mysql-data:
  envcard-mysql-log:
  minio_data:
  redis-data:
services:
  # TODO: Link volume ของไฟล์ Assets ทุกตัวก่อน Prod
  envcard-mysql:
    image: mysql:8
    container_name: envcard-mysql
    env_file:
      - docker.env
    ports:
      - '3311:3306'
    volumes:
      - envcard-mysql-data:/var/lib/mysql
      - envcard-mysql-log:/var/log/mysql
    networks:
      - envcard-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  seeder:
    container_name: seeder
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file:
      - /src/seeder.env
    depends_on:
      envcard-mysql:
        condition: service_healthy
    command: ['npm', 'run', 'start:seed']
    restart: no
    networks:
      - envcard-network
    profiles:
      - 'seed'
  envcard-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - /src/.env
    ports:
      - '3002:3000'
    depends_on:
      envcard-mysql:
        condition: service_healthy

    restart: always
    networks:
      - envcard-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - 'dev'

  envcard-api-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - /src/.env
    ports:
      - '3002:3000'
    depends_on:
      envcard-mysql:
        condition: service_healthy

    restart: always
    networks:
      - envcard-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - 'prod'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: envcard-mysql
    restart: always
    ports:
      - '8082:80'
    networks:
      - envcard-network
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - envcard-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

  redis-ui:
    image: redis/redisinsight:latest
    container_name: redis-ui
    depends_on:
      - redis
    ports:
      - '5540:5540'
    volumes:
      - redis-data:/data
