networks:
  envcard-network:
    driver: bridge
volumes:
  envcard-mysql-data:
  envcard-mysql-log:
services:
  # TODO: Link volume ของไฟล์ Assets ทุกตัวก่อน Prod
  envcard-mysql:
    image: mysql:8
    container_name: envcard-mysql
    env_file:
      - docker.env
    ports:
      - '3311:3306'
    volumes:
      - envcard-mysql-data:/var/lib/mysql
      - envcard-mysql-log:/var/log/mysql
      - /config/my.conf:/etc/mysql/conf.d/config-file.cnf
      - /init:/docker-entrypoint-initdb.d
    networks:
      - envcard-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
  envcard-api-fresh:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - /src/.env
    ports:
      - '3000:3000'
    depends_on:
      envcard-mysql:
        condition: service_healthy
    restart: always
    networks:
      - envcard-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - 'fresh'
  envcard-api-update:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod-no-seed
    env_file:
      - /src/.env
    ports:
      - '3000:3000'
    depends_on:
      envcard-mysql:
        condition: service_healthy
    restart: always
    networks:
      - envcard-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - 'prod-update'
  envcard-api-dev-fresh:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-migrate-seed
    env_file:
      - /src/.env
    ports:
      - '3000:3000'
    depends_on:
      envcard-mysql:
        condition: service_healthy
    restart: always
    networks:
      - envcard-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - 'dev-fresh'
  envcard-api-dev-update:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - /src/.env
    ports:
      - '3000:3000'
    depends_on:
      envcard-mysql:
        condition: service_healthy
    restart: always
    networks:
      - envcard-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - 'dev-update'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    profiles:
      - 'dev'
      - 'dev-fresh'
    container_name: phpmyadmin
    environment:
      PMA_HOST: envcard-mysql
    restart: always
    ports:
      - '8082:80'
    networks:
      - envcard-network
